// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package questing

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// BurnBalls is the `burnBalls` instruction.
type BurnBalls struct {
	QuestIndex *uint64

	// [0] = [WRITE] ballzTokenAccount
	//
	// [1] = [WRITE] ballzMint
	//
	// [2] = [WRITE, SIGNER] initializer
	//
	// [3] = [WRITE] questAccount
	//
	// [4] = [] systemProgram
	//
	// [5] = [] tokenProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewBurnBallsInstructionBuilder creates a new `BurnBalls` instruction builder.
func NewBurnBallsInstructionBuilder() *BurnBalls {
	nd := &BurnBalls{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 6),
	}
	return nd
}

// SetQuestIndex sets the "questIndex" parameter.
func (inst *BurnBalls) SetQuestIndex(questIndex uint64) *BurnBalls {
	inst.QuestIndex = &questIndex
	return inst
}

// SetBallzTokenAccountAccount sets the "ballzTokenAccount" account.
func (inst *BurnBalls) SetBallzTokenAccountAccount(ballzTokenAccount ag_solanago.PublicKey) *BurnBalls {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(ballzTokenAccount).WRITE()
	return inst
}

// GetBallzTokenAccountAccount gets the "ballzTokenAccount" account.
func (inst *BurnBalls) GetBallzTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetBallzMintAccount sets the "ballzMint" account.
func (inst *BurnBalls) SetBallzMintAccount(ballzMint ag_solanago.PublicKey) *BurnBalls {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(ballzMint).WRITE()
	return inst
}

// GetBallzMintAccount gets the "ballzMint" account.
func (inst *BurnBalls) GetBallzMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetInitializerAccount sets the "initializer" account.
func (inst *BurnBalls) SetInitializerAccount(initializer ag_solanago.PublicKey) *BurnBalls {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(initializer).WRITE().SIGNER()
	return inst
}

// GetInitializerAccount gets the "initializer" account.
func (inst *BurnBalls) GetInitializerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetQuestAccountAccount sets the "questAccount" account.
func (inst *BurnBalls) SetQuestAccountAccount(questAccount ag_solanago.PublicKey) *BurnBalls {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(questAccount).WRITE()
	return inst
}

// GetQuestAccountAccount gets the "questAccount" account.
func (inst *BurnBalls) GetQuestAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *BurnBalls) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *BurnBalls {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *BurnBalls) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *BurnBalls) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *BurnBalls {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *BurnBalls) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

func (inst BurnBalls) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_BurnBalls,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst BurnBalls) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *BurnBalls) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.QuestIndex == nil {
			return errors.New("QuestIndex parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.BallzTokenAccount is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.BallzMint is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Initializer is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.QuestAccount is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
	}
	return nil
}

func (inst *BurnBalls) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("BurnBalls")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("QuestIndex", *inst.QuestIndex))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=6]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("   ballzToken", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("    ballzMint", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("  initializer", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("        quest", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("systemProgram", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta(" tokenProgram", inst.AccountMetaSlice.Get(5)))
					})
				})
		})
}

func (obj BurnBalls) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `QuestIndex` param:
	err = encoder.Encode(obj.QuestIndex)
	if err != nil {
		return err
	}
	return nil
}
func (obj *BurnBalls) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `QuestIndex`:
	err = decoder.Decode(&obj.QuestIndex)
	if err != nil {
		return err
	}
	return nil
}

// NewBurnBallsInstruction declares a new BurnBalls instruction with the provided parameters and accounts.
func NewBurnBallsInstruction(
	// Parameters:
	questIndex uint64,
	// Accounts:
	ballzTokenAccount ag_solanago.PublicKey,
	ballzMint ag_solanago.PublicKey,
	initializer ag_solanago.PublicKey,
	questAccount ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey) *BurnBalls {
	return NewBurnBallsInstructionBuilder().
		SetQuestIndex(questIndex).
		SetBallzTokenAccountAccount(ballzTokenAccount).
		SetBallzMintAccount(ballzMint).
		SetInitializerAccount(initializer).
		SetQuestAccountAccount(questAccount).
		SetSystemProgramAccount(systemProgram).
		SetTokenProgramAccount(tokenProgram)
}
