// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package questing

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// TransferPixelballz is the `transferPixelballz` instruction.
type TransferPixelballz struct {
	QuestIndex *uint64

	// [0] = [WRITE] depositTokenAccount
	//
	// [1] = [WRITE] pixelballzMint
	//
	// [2] = [WRITE] pixelballzTokenAccount
	//
	// [3] = [WRITE, SIGNER] initializer
	//
	// [4] = [WRITE] questAccount
	//
	// [5] = [] systemProgram
	//
	// [6] = [] tokenProgram
	//
	// [7] = [] rent
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewTransferPixelballzInstructionBuilder creates a new `TransferPixelballz` instruction builder.
func NewTransferPixelballzInstructionBuilder() *TransferPixelballz {
	nd := &TransferPixelballz{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 8),
	}
	return nd
}

// SetQuestIndex sets the "questIndex" parameter.
func (inst *TransferPixelballz) SetQuestIndex(questIndex uint64) *TransferPixelballz {
	inst.QuestIndex = &questIndex
	return inst
}

// SetDepositTokenAccountAccount sets the "depositTokenAccount" account.
func (inst *TransferPixelballz) SetDepositTokenAccountAccount(depositTokenAccount ag_solanago.PublicKey) *TransferPixelballz {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(depositTokenAccount).WRITE()
	return inst
}

// GetDepositTokenAccountAccount gets the "depositTokenAccount" account.
func (inst *TransferPixelballz) GetDepositTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetPixelballzMintAccount sets the "pixelballzMint" account.
func (inst *TransferPixelballz) SetPixelballzMintAccount(pixelballzMint ag_solanago.PublicKey) *TransferPixelballz {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(pixelballzMint).WRITE()
	return inst
}

// GetPixelballzMintAccount gets the "pixelballzMint" account.
func (inst *TransferPixelballz) GetPixelballzMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetPixelballzTokenAccountAccount sets the "pixelballzTokenAccount" account.
func (inst *TransferPixelballz) SetPixelballzTokenAccountAccount(pixelballzTokenAccount ag_solanago.PublicKey) *TransferPixelballz {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(pixelballzTokenAccount).WRITE()
	return inst
}

// GetPixelballzTokenAccountAccount gets the "pixelballzTokenAccount" account.
func (inst *TransferPixelballz) GetPixelballzTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetInitializerAccount sets the "initializer" account.
func (inst *TransferPixelballz) SetInitializerAccount(initializer ag_solanago.PublicKey) *TransferPixelballz {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(initializer).WRITE().SIGNER()
	return inst
}

// GetInitializerAccount gets the "initializer" account.
func (inst *TransferPixelballz) GetInitializerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetQuestAccountAccount sets the "questAccount" account.
func (inst *TransferPixelballz) SetQuestAccountAccount(questAccount ag_solanago.PublicKey) *TransferPixelballz {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(questAccount).WRITE()
	return inst
}

// GetQuestAccountAccount gets the "questAccount" account.
func (inst *TransferPixelballz) GetQuestAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *TransferPixelballz) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *TransferPixelballz {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *TransferPixelballz) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *TransferPixelballz) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *TransferPixelballz {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *TransferPixelballz) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetRentAccount sets the "rent" account.
func (inst *TransferPixelballz) SetRentAccount(rent ag_solanago.PublicKey) *TransferPixelballz {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(rent)
	return inst
}

// GetRentAccount gets the "rent" account.
func (inst *TransferPixelballz) GetRentAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

func (inst TransferPixelballz) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_TransferPixelballz,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst TransferPixelballz) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *TransferPixelballz) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.QuestIndex == nil {
			return errors.New("QuestIndex parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.DepositTokenAccount is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.PixelballzMint is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.PixelballzTokenAccount is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.Initializer is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.QuestAccount is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.Rent is not set")
		}
	}
	return nil
}

func (inst *TransferPixelballz) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("TransferPixelballz")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("QuestIndex", *inst.QuestIndex))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=8]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("   depositToken", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta(" pixelballzMint", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("pixelballzToken", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("    initializer", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("          quest", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("  systemProgram", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("   tokenProgram", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("           rent", inst.AccountMetaSlice.Get(7)))
					})
				})
		})
}

func (obj TransferPixelballz) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `QuestIndex` param:
	err = encoder.Encode(obj.QuestIndex)
	if err != nil {
		return err
	}
	return nil
}
func (obj *TransferPixelballz) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `QuestIndex`:
	err = decoder.Decode(&obj.QuestIndex)
	if err != nil {
		return err
	}
	return nil
}

// NewTransferPixelballzInstruction declares a new TransferPixelballz instruction with the provided parameters and accounts.
func NewTransferPixelballzInstruction(
	// Parameters:
	questIndex uint64,
	// Accounts:
	depositTokenAccount ag_solanago.PublicKey,
	pixelballzMint ag_solanago.PublicKey,
	pixelballzTokenAccount ag_solanago.PublicKey,
	initializer ag_solanago.PublicKey,
	questAccount ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey,
	rent ag_solanago.PublicKey) *TransferPixelballz {
	return NewTransferPixelballzInstructionBuilder().
		SetQuestIndex(questIndex).
		SetDepositTokenAccountAccount(depositTokenAccount).
		SetPixelballzMintAccount(pixelballzMint).
		SetPixelballzTokenAccountAccount(pixelballzTokenAccount).
		SetInitializerAccount(initializer).
		SetQuestAccountAccount(questAccount).
		SetSystemProgramAccount(systemProgram).
		SetTokenProgramAccount(tokenProgram).
		SetRentAccount(rent)
}
