// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package questing

import ag_binary "github.com/gagliardetto/binary"

type QuestError ag_binary.BorshEnum

const (
	QuestErrorUnexpectedQuestingState QuestError = iota
	QuestErrorInvalidInitializer
	QuestErrorIsTimelocked
)

func (value QuestError) String() string {
	switch value {
	case QuestErrorUnexpectedQuestingState:
		return "UnexpectedQuestingState"
	case QuestErrorInvalidInitializer:
		return "InvalidInitializer"
	case QuestErrorIsTimelocked:
		return "IsTimelocked"
	default:
		return ""
	}
}
